name: Acountpro
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.1
  open_file: ^3.3.2
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo1.png

# ------------------------
# APP ICON CONFIG
# ------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  min_sdk_android: 21

# ------------------------
# SPLASH SCREEN CONFIG
# ------------------------
flutter_native_splash:
  color: "#000000"              # Background color (black)
  image: assets/images/logo1.png
  android: true
  ios: true
  web: true
